# AI LAB 9
### NAME : MINHA MAHMOOD
### ROLL NO: BSAIM-F24-099

Using <b> Python </b> v3.135
<hr>
with <b> Jupyter Notebook </b>v7.5

<div class ="alert alert-block alert-warning">
 Using <b style = "color:orange"> Python </b> v3.135
<hr>
with <b> Jupyter Notebook </b>v7.5
</div>

<div class ="alert alert-block alert-info">
  Import <b>Libraries</b>
</div>

In [ ]:
%ls

 Volume in drive C has no label.
 Volume Serial Number is E0C3-156F

 Directory of c:\Users\Lenovo L380 A&I\Downloads\archive (7)

28/10/2025  14:23    <DIR>          .
28/10/2025  14:21    <DIR>          ..
28/10/2025  14:21           526,795 data.csv
28/10/2025  14:21         1,721,295 data.dat
28/10/2025  14:21           526,795 output.csv
28/10/2025  14:23             1,077 project ai.ipynb
               4 File(s)      2,775,962 bytes
               2 Dir(s)  44,435,165,184 bytes free

<div class ="alert alert-block alert-info">
1. <b>Data Gathering</b>
</div>

In [1]:
#!pip install pandas
import pandas as pd

<div class ="alert alert-block alert-info">
2. <b>Data Loading</b>
</div>

In [2]:
df=pd.read_csv("data.csv")
# df=pd.read_json("")
df
print()

<div class ="alert alert-block alert-info">
3. <b>Data exploration</b>
</div>

In [3]:
df.head()
#tells ist 5 rows

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
0,2014-05-02 00:00:00,313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,0,1955,2005,18810 Densmore Ave N,Shoreline,WA 98133,USA
1,2014-05-02 00:00:00,2384000.0,5.0,2.50,3650,9050,2.0,0,4,5,3370,280,1921,0,709 W Blaine St,Seattle,WA 98119,USA
2,2014-05-02 00:00:00,342000.0,3.0,2.00,1930,11947,1.0,0,0,4,1930,0,1966,0,26206-26214 143rd Ave SE,Kent,WA 98042,USA
3,2014-05-02 00:00:00,420000.0,3.0,2.25,2000,8030,1.0,0,0,4,1000,1000,1963,0,857 170th Pl NE,Bellevue,WA 98008,USA
4,2014-05-02 00:00:00,550000.0,4.0,2.50,1940,10500,1.0,0,0,4,1140,800,1976,1992,9105 170th Ave NE,Redmond,WA 98052,USA

In [4]:
df.tail()
# last five rowa

,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip,country
4595,2014-07-09 00:00:00,308166.666667,3.0,1.75,1510,6360,1.0,0,0,4,1510,0,1954,1979,501 N 143rd St,Seattle,WA 98133,USA
4596,2014-07-09 00:00:00,534333.333333,3.0,2.50,1460,7573,2.0,0,0,3,1460,0,1983,2009,14855 SE 10th Pl,Bellevue,WA 98007,USA
4597,2014-07-09 00:00:00,416904.166667,3.0,2.50,3010,7014,2.0,0,0,3,3010,0,2009,0,759 Ilwaco Pl NE,Renton,WA 98059,USA
4598,2014-07-10 00:00:00,203400.000000,4.0,2.00,2090,6630,1.0,0,0,3,1070,1020,1974,0,5148 S Creston St,Seattle,WA 98178,USA
4599,2014-07-10 00:00:00,220600.000000,3.0,2.50,1490,8102,2.0,0,0,4,1490,0,1990,0,18717 SE 258th St,Covington,WA 98042,USA

In [5]:
df.describe()
# tells numeric value

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
count,4.600000e+03,4600.000000,4600.000000,4600.000000,4.600000e+03,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000,4600.000000
mean,5.519630e+05,3.400870,2.160815,2139.346957,1.485252e+04,1.512065,0.007174,0.240652,3.451739,1827.265435,312.081522,1970.786304,808.608261
std,5.638347e+05,0.908848,0.783781,963.206916,3.588444e+04,0.538288,0.084404,0.778405,0.677230,862.168977,464.137228,29.731848,979.414536
min,0.000000e+00,0.000000,0.000000,370.000000,6.380000e+02,1.000000,0.000000,0.000000,1.000000,370.000000,0.000000,1900.000000,0.000000
25%,3.228750e+05,3.000000,1.750000,1460.000000,5.000750e+03,1.000000,0.000000,0.000000,3.000000,1190.000000,0.000000,1951.000000,0.000000
50%,4.609435e+05,3.000000,2.250000,1980.000000,7.683000e+03,1.500000,0.000000,0.000000,3.000000,1590.000000,0.000000,1976.000000,0.000000
75%,6.549625e+05,4.000000,2.500000,2620.000000,1.100125e+04,2.000000,0.000000,0.000000,4.000000,2300.000000,610.000000,1997.000000,1999.000000
max,2.659000e+07,9.000000,8.000000,13540.000000,1.074218e+06,3.500000,1.000000,4.000000,5.000000,9410.000000,4820.000000,2014.000000,2014.000000

In [6]:
df.info()
# total values and null values nA(empty cells)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           4600 non-null   object
 1   price          4600 non-null   float64
 2   bedrooms       4600 non-null   float64
 3   bathrooms      4600 non-null   float64
 4   sqft_living    4600 non-null   int64
 5   sqft_lot       4600 non-null   int64
 6   floors         4600 non-null   float64
 7   waterfront     4600 non-null   int64
 8   view           4600 non-null   int64
 9   condition      4600 non-null   int64
 10  sqft_above     4600 non-null   int64
 11  sqft_basement  4600 non-null   int64
 12  yr_built       4600 non-null   int64
 13  yr_renovated   4600 non-null   int64
 14  street         4600 non-null   object
 15  city           4600 non-null   object
 16  statezip       4600 non-null   object
 17  country        4600 non-null   object
dtypes: float64(4), int64(9), object(5)
memory usage: 647.0+ KB

In [7]:
df.count()
# agar mein 1 likho ghi tou ye 1 index oar btae gh

date             4600
price            4600
bedrooms         4600
bathrooms        4600
sqft_living      4600
sqft_lot         4600
floors           4600
waterfront       4600
view             4600
condition        4600
sqft_above       4600
sqft_basement    4600
yr_built         4600
yr_renovated     4600
street           4600
city             4600
statezip         4600
country          4600
dtype: int64

In [8]:
df['city'].unique()
#unique cities btae gha jo baar baaar repeat ho rahi

array(['Shoreline', 'Seattle', 'Kent', 'Bellevue', 'Redmond',
       'Maple Valley', 'North Bend', 'Lake Forest Park', 'Sammamish',
       'Auburn', 'Des Moines', 'Bothell', 'Federal Way', 'Kirkland',
       'Issaquah', 'Woodinville', 'Normandy Park', 'Fall City', 'Renton',
       'Carnation', 'Snoqualmie', 'Duvall', 'Burien', 'Covington',
       'Inglewood-Finn Hill', 'Kenmore', 'Newcastle', 'Mercer Island',
       'Black Diamond', 'Ravensdale', 'Clyde Hill', 'Algona', 'Skykomish',
       'Tukwila', 'Vashon', 'Yarrow Point', 'SeaTac', 'Medina',
       'Enumclaw', 'Snoqualmie Pass', 'Pacific', 'Beaux Arts Village',
       'Preston', 'Milton'], dtype=object)

In [9]:
df.nunique()
# no of unique values btae gha

date               70
price            1741
bedrooms           10
bathrooms          26
sqft_living       566
sqft_lot         3113
floors              6
waterfront          2
view                5
condition           5
sqft_above        511
sqft_basement     207
yr_built          115
yr_renovated       60
street           4525
city               44
statezip           77
country             1
dtype: int64

In [10]:
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'street', 'city',
       'statezip', 'country'],
      dtype='object')

In [11]:
for col in df.columns:
    print(col)
#arranged form mein deta column

date
price
bedrooms
bathrooms
sqft_living
sqft_lot
floors
waterfront
view
condition
sqft_above
sqft_basement
yr_built
yr_renovated
street
city
statezip
country

In [12]:
df.isnull().sum()
# returns true false values if there is null value or not
#sum hamne islia use kia bcz ye true false ko count kr k btae gha

date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
street           0
city             0
statezip         0
country          0
dtype: int64

<div class="alert alert-block alert-info">
    1. <b>lab 10</b>
</div>

<div class="alert alert-block alert-info">
    4. <b>Data Pre-Processing</b>
</div>

<div class="alert alert-block alert-danger">
    4.1. <b>Manage Null Values</b>
</div>

In [13]:
# df.drop('date', axis=1, inplace=True)
df = df.drop('date', axis=1)

In [14]:
# df.drop('country', axis=1, inplace=True)
df = df.drop('country', axis=1)

In [15]:
# For Object
def fillnaObjectMode(cols):
    for i in cols:
        df[i] = df[i].fillna(df[i].mode()[0])

columns = ['city', 'street', 'statezip']
fillnaObjectMode(columns)

In [16]:
# For Int Type
def fillnaIntMode(cols):
    for i in cols:
        df[i] = df[i].fillna(df[i].mode()[0])

columns = ['bedrooms','bathrooms','floors','waterfront','view','yr_built','yr_renovated']
fillnaIntMode(columns)

In [17]:
# For Float 
def fillnaFloatMean(cols):
    for i in cols:
        df[i] = df[i].fillna(df[i].mean())

columns = ['price','condition','sqft_living','sqft_lot','sqft_above','sqft_basement']
fillnaFloatMean(columns)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          4600 non-null   float64
 1   bedrooms       4600 non-null   float64
 2   bathrooms      4600 non-null   float64
 3   sqft_living    4600 non-null   int64
 4   sqft_lot       4600 non-null   int64
 5   floors         4600 non-null   float64
 6   waterfront     4600 non-null   int64
 7   view           4600 non-null   int64
 8   condition      4600 non-null   int64
 9   sqft_above     4600 non-null   int64
 10  sqft_basement  4600 non-null   int64
 11  yr_built       4600 non-null   int64
 12  yr_renovated   4600 non-null   int64
 13  street         4600 non-null   object
 14  city           4600 non-null   object
 15  statezip       4600 non-null   object
dtypes: float64(4), int64(9), object(3)
memory usage: 575.1+ KB

<div class="alert alert-block alert-danger">
    4.2. <b>Manage Data Types</b>
</div>

In [20]:
df['price'] = df['price'].astype('int64')

In [21]:
# For Float 
def changeFloatToInt(cols):
    for i in cols:
        df[i] = df[i].astype('int64')

columns = ['price','condition','sqft_living','sqft_lot','sqft_above',
           'sqft_basement','bedrooms','bathrooms','floors','waterfront',
           'view','yr_built','yr_renovated']
changeFloatToInt(columns)

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          4600 non-null   int64
 1   bedrooms       4600 non-null   int64
 2   bathrooms      4600 non-null   int64
 3   sqft_living    4600 non-null   int64
 4   sqft_lot       4600 non-null   int64
 5   floors         4600 non-null   int64
 6   waterfront     4600 non-null   int64
 7   view           4600 non-null   int64
 8   condition      4600 non-null   int64
 9   sqft_above     4600 non-null   int64
 10  sqft_basement  4600 non-null   int64
 11  yr_built       4600 non-null   int64
 12  yr_renovated   4600 non-null   int64
 13  street         4600 non-null   object
 14  city           4600 non-null   object
 15  statezip       4600 non-null   object
dtypes: int64(13), object(3)
memory usage: 575.1+ KB

In [ ]:
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [ ]:
def convertObjToInt(cols):
    for i in cols:
        data = pd.DataFrame({i:df[i].unique()})
        data_LE = LabelEncoder()
        data_LE.fit(np.ravel(data)) 
        df[i] = data_LE.transform(df[i])
        
columns = ['street', 'city', 'statezip']
convertObjToInt(columns)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   price          4600 non-null   int64
 1   bedrooms       4600 non-null   int64
 2   bathrooms      4600 non-null   int64
 3   sqft_living    4600 non-null   int64
 4   sqft_lot       4600 non-null   int64
 5   floors         4600 non-null   int64
 6   waterfront     4600 non-null   int64
 7   view           4600 non-null   int64
 8   condition      4600 non-null   int64
 9   sqft_above     4600 non-null   int64
 10  sqft_basement  4600 non-null   int64
 11  yr_built       4600 non-null   int64
 12  yr_renovated   4600 non-null   int64
 13  street         4600 non-null   int64
 14  city           4600 non-null   int64
 15  statezip       4600 non-null   int64
dtypes: int64(16)
memory usage: 575.1 KB

In [27]:
df.head(2)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip
0,313000,3,1,1340,7912,1,0,0,3,1340,0,1955,2005,1522,36,62
1,2384000,5,2,3650,9050,2,0,4,5,3370,280,1921,0,3899,35,58

In [28]:
df.to_csv('processed_data.csv', index=False, header=True)

In [29]:
df = pd.read_csv('processed_data.csv')
df

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated,street,city,statezip
0,313000,3,1,1340,7912,1,0,0,3,1340,0,1955,2005,1522,36,62
1,2384000,5,2,3650,9050,2,0,4,5,3370,280,1921,0,3899,35,58
2,342000,3,2,1930,11947,1,0,0,4,1930,0,1966,0,2291,18,26
3,420000,3,2,2000,8030,1,0,0,4,1000,1000,1963,0,4263,3,7
4,550000,4,2,1940,10500,1,0,0,4,1140,800,1976,1992,4352,31,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4595,308166,3,1,1510,6360,1,0,0,4,1510,0,1954,1979,3447,35,62
4596,534333,3,2,1460,7573,2,0,0,3,1460,0,1983,2009,960,3,6
4597,416904,3,2,3010,7014,2,0,0,3,3010,0,2009,0,4033,32,37
4598,203400,4,2,2090,6630,1,0,0,3,1070,1020,1974,0,3498,35,71
4599,220600,3,2,1490,8102,2,0,0,4,1490,0,1990,0,1514,9,26